
[[mgr.prepend_keymap]]
on = ["c", "p"]
run = "plugin convert -- --extension='png'"
desc = "Convert selected files to PNG"

[[mgr.prepend_keymap]]
on = ["c", "j"]
run = "plugin convert -- --extension='jpg'"
desc = "Convert selected files to JPG"

[[mgr.prepend_keymap]]
on = ["c", "w"]
run = "plugin convert -- --extension='webp'"
desc = "Convert selected files to WebP"
